import { PopUp } from "popup.slint";
import { Button, LineEdit } from "std-widgets.slint";
export component CreatePopUp {
    in-out property <string> name:"";
    in property <string> placeholder;
    in property <string> error: "";
    callback on_close();
    callback on_confirm(name: string);

    PopUp {
        Dialog {
            title: "Create";

            VerticalLayout {
                padding: 16px;
                spacing: 10px;

                LineEdit {
                    placeholder-text: root.placeholder;
                    text <=> root.name;
                }

                if root.error != "": Text {
                    text: root.error;
                    color: red;
                }

                HorizontalLayout {
                    spacing: 10px;

                    Button {
                        text: "Close";

                        clicked => {
                            on_close()
                        }
                    }

                    Button {
                        text: "Confirm";
                        enabled: !root.name.is-empty;

                        clicked => {
                            root.on_confirm(root.name)
                        }
                    }
                }
            }
        }
    }
}
