import { PopUp } from "popup.slint";
import { Button, LineEdit } from "std-widgets.slint";
export component CreatePopUp {
    in-out property <string> name:"";
    in property <string> placeholder;
    in property <string> error: "";

    property <string> last-valid: "";
    property <bool> focused:false;

    callback on_close();
    callback on_confirm(name: string);
    pure callback validate_name(name: string) -> bool;

    PopUp {
        Dialog {
            title: "Create";

            VerticalLayout {
                padding: 16px;
                spacing: 10px;

                le := LineEdit {
                    placeholder-text: root.placeholder;
                    text: root.name;

                    edited(text) => {
                        if text.is-empty || root.validate_name(text) {
                            root.last-valid = text;
                            root.name = text;
                        } else {
                            root.name = root.last-valid;
                            self.text = root.last-valid;
                        }
                    }

                    accepted(text) => {
                        root.on_confirm(root.name)
                    }
                }

                if root.error != "": Text {
                    text: root.error;
                    color: red;
                }

                HorizontalLayout {
                    spacing: 10px;

                    Button {
                        text: "Confirm";
                        enabled: !root.name.is-empty;

                        clicked => {
                            root.on_confirm(root.name)
                        }
                    }

                    Button {
                        text: "Close";

                        clicked => {
                            on_close()
                        }
                    }
                }
            }
        }
    }

    init => {
        le.focus()
    }
}
