import { Palette, VerticalBox, HorizontalBox } from "std-widgets.slint";


component NavBarItem inherits Rectangle {
    in property <bool> enabled;
    in property <bool> selected;
    in property <bool> has-focus;
    in-out property <string> text <=> label.text;
    callback clicked <=> touch.clicked;
    min-height: l.preferred-height + 10px;
    states [
        pressed when root.enabled && touch.pressed: {
            state.opacity: 0.8;
        }
        hover when root.enabled && touch.has-hover: {
            state.opacity: 0.6;
        }
        selected when root.enabled && root.selected: {
            state.opacity: 1;
        }
        focused when root.enabled && root.has-focus: {
            state.opacity: 0.8;
        }
    ]

    state := Rectangle {
        opacity: 0;
        background: Palette.selection-background;
        animate opacity { duration: 150ms; }
        height: l.preferred-height;
    }

    l := HorizontalBox {
        spacing: 0px;
        label := Text {
            color: Palette.foreground;
            vertical-alignment: center;
            horizontal-alignment: center;
            font-size: 14px;
        }
    }

    touch := TouchArea {
        width: 100%;
        height: 100%;
    }
}


export component NavBar inherits Rectangle {
    in property <[string]> entries:[];
    in property <bool> enabled;
    in property <bool> name;
    in-out property <int> current-item:0;
    out property <int> current-focused: fs.has-focus ? fs.focused-tab : -1;
    callback changed-selection(sel: int);

    forward-focus: fs;
    accessible-role: tab;
    accessible-delegate-focus: root.current-focused >= 0 ? root.current-focused : root.current-item;
    Rectangle {
        background: Palette.alternate-background;
        fs := FocusScope {
            key-pressed(event) => {
                if (enabled) {
                    if (event.text == "\n") {
                        root.current-item = root.current-focused;
                        return accept;
                    }
                    if (event.text == Key.UpArrow) {
                        self.focused-tab = Math.max(self.focused-tab - 1,  0);
                        return accept;
                    }
                    if (event.text == Key.DownArrow) {
                        self.focused-tab = Math.min(self.focused-tab + 1, root.entries.length - 1);
                        return accept;
                    }
                }
                return reject;
            }
            key-released(event) => {
                if (enabled && event.text == " ") {
                    root.current-item = root.current-focused;
                    return accept;
                }
                return reject;
            }
            property <int> focused-tab: 0;
            x: 0;
            width: 0;
        }
    }

    VerticalLayout {
        alignment: start;
        vertical-stretch: 0;
        padding: 0px;
        for item[index] in root.entries: NavBarItem {
            clicked => {
                if root.enabled {
                    root.current-item = index;
                    root.changed-selection(index);
                }
            }
            enabled: root.enabled;
            has-focus: index == root.current-focused;
            text: item;
            selected: index == root.current-item;
        }
    }
}
