[package]
name = "git-flow-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = "1"
rfd = "0"
fwkarq = "1"
tokio = "1"
regex = "1"
git-flow-rs-core = "1"

[build-dependencies]
slint-build = "1"


[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"
opt-level = 3
