// ui/app.slint

import { Button, ListView, LineEdit } from "std-widgets.slint";
import { NavBar } from "components/navbar.slint";
import { MainMenu } from "components/main_menu.slint";
import { CreatePopUp } from "components/create_popup.slint";
import { ConsolePopUp } from "components/console_popup.slint";
import { FinishPopup } from "components/finish_popup.slint";
import { PopUp } from "components/popup.slint";
import { DevelopPopup } from "components/develop_popup.slint";
export component App inherits Window {
    in property <bool> not_a_repository:false;
    in property <string> repository: "";
    in property <string> create-err: "";
    in property <[string]> items;
    in property <string> console_text: "";
    in property <bool> dirty:true;

    in-out property <bool> console_finished:false;
    in-out property <bool> show_develop_dialog:true;
    in-out property <bool> show_console_dialog:false;
    in-out property <bool> show_start_dialog:false;
    in-out property <bool> show_finish_dialog:false;
    in-out property <int> item: -1;

    out property <int> category: 0;

    property <string> start_text: category == 0 ? "Enter feature name" : category == 1 ? "Enter release name" : category == 2 ? "Enter bugfix name" : "Enter hotfix name";

    callback refresh_items(kind: int);
    callback start_flow(kind: int, name: string);
    callback finish_flow(kind: int, name: string);
    callback create_develop_branch();
    callback quit_application();
    pure callback validate_name(name: string) -> bool;

    width: 500px;
    height: root.not_a_repository ? 100px : 400px;
    title: "Git flow @ " + root.repository;
    icon: @image-url("../../resources/assets/icon.png");

    if root.not_a_repository: Rectangle {
        width: 300px;
        height: 150px;

        Text {
            text: "No repository found in " + root.repository;
        }
    }

    if !root.not_a_repository: Rectangle {
        if root.show_develop_dialog: DevelopPopup {
            width: 100%;
            height: 100%;
            z: 100;

            on_close => {
                root.quit_application();
            }
            on_confirm() => {
                root.create_develop_branch()
            }
        }

        if root.show_start_dialog: CreatePopUp {
            width: 100%;
            height: 100%;
            z: 100;
            placeholder: start_text;
            error: root.create-err;

            on_close => {
                root.show_start_dialog = false;
            }
            on_confirm(name) => {
                root.start_flow(root.category,name)
            }
            validate_name(name) => {
                root.validate_name(name)
            }
        }

        if root.show_finish_dialog: FinishPopup {
            width: 100%;
            height: 100%;
            z: 100;
            name: items[item];

            on_close => {
                root.show_finish_dialog = false;
            }
            on_confirm(name) => {
                root.finish_flow(root.category,name)
            }
        }

        if root.show_console_dialog: ConsolePopUp {
            width: 100%;
            height: 100%;
            z: 100;
            body: root.console_text;
            finished: root.console_finished;

            on_close => {
                root.show_console_dialog = false;
            }
        }

        mm := MainMenu {
            width: 100%;
            height: 100%;
            enabled: !root.show_start_dialog;
            items: items;
            current-category <=> category;
            current-item <=> item;
            dirty: root.dirty;
            category-changes() => {
                root.refresh_items(root.category);
            }
            create-requested() => {
                root.show_start_dialog = true;
            }
            finish-requested() => {
                root.show_finish_dialog = true;
            }
        }
    }
}
