[package]
name = "git-flow-rs-core"
version = "2.1.0"
edition = "2024"
description = "Git flow implementation enriched with business logic"
license = "MIT OR Apache-2.0"


[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
fwkarq = { version = "1.2.4", features = ["shell"] }
thiserror = "2.0.18"
